title: "James Tizard"
theme: jekyll-theme-primer

plugins:
  - jekyll-scholar
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

scholar:
  style: _bibliography/acm-sigchi-proceedings.csl
  locale: en

  # Sorting / grouping
  sort_by: ordering, author
  order: ascending
  group_by: year
  group_order: descending

  # Sources
  source: _bibliography
  bibliography: references.bib

  # Output shaping
  replace_strings: true
  join_strings: true
  bibliography_list_tag: div
  bibliography_item_tag: span

  # Skip fields you don't want printed
  bibtex_skip_fields: [pdf, code, video, slides, ordering]

  # Show everything unless filtered in-page
  query: "@*"
